include:
  - 'https://gitlab.com/legoktm/rust-ci-pipeline/-/raw/master/jobs.yml'

variables:
  APT_PACKAGES: libssl-dev
  DNF_PACKAGES: openssl-devel
  CARGO_AUDIT: --ignore RUSTSEC-2020-0016
  SKIP_COVERAGE: "yes"

rust-coverage:
  extends: .rust-coverage
  allow_failure: true

pages:
  extends: .pages
